mongodb:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
pm2:
  image: keymetrics/pm2-docker-alpine
  volumes:
    - .:/app
  ports:
    - "80:3000"
  links:
    - mongodb
  environment:
    PORT: 3000
